### ISSUE TITLE
Using node as a dependancy for install.

### ISSUE THREAD

**Issue by sealneaward** [suthar26/FRC-scouting-app#5]
You guys should not have node as a dependancy in your package.json when installing your repo. I had difficulty installing this because that version of node does not work on my version of linux.

```
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "node"
npm ERR! node v9.2.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node@9.2.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node@9.2.0 preinstall script 'node installArchSpecificPackage'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

```

**Comment by suthar26** [comment]
Would you like me to make changes?

**Comment by sealneaward** [comment]
It's fine. I made a pull request. Can you approve it?

https://github.com/suthar26/FRC-scouting-app/pull/6
